export default {
  locations: ["Melbourne", "Sydney", "Brisbane", "Gold Coast", "Adelaide"],
  default: ["Option A", "Option B", "Option C"],
  currency: ["AUD", "USD", "INR"],
  rateTypes: ["Contract", "Full Time", "Part Time", "Casual"],
  defaultFormData: {
    heading: "",
    client: "",
    industry: "",
    jobType: "",
    skills: "",
    description: "",
    location: "",
    contact: "",
    email: "",
    phoneNo: "",
    jobCandidateRating: "",
    jobStage: "",
    salary: "",
    currency: "",
  },
};
